name: tests

on:
  - push

env:
  CI: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17.x
      - run: npm install
      - run: npm test
